<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'pre_title_format'				=> "[%s] ",
'pre_tags_disabled'				=> "Tags have been disabled in this forum.",
'pre_select'				=> "-- Select One --",
'pre_none_entered'				=> "You must select a topic prefix to post in this forum.",
'pre_none'				=> "None",
'pre_cats'				=> "<b>Categories:</b>",
'pre_topic_prefix'				=> "Topic Prefix",
 ); 
