<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'Badges_title'				=> "Badges Title",
'no_Badges_groups'				=> "You did not enter any groups for the Badge.",
'Badges_form_detail_edit'				=> "Use this form to edit this Badges.",
'Badges_form_detail_new'				=> "Use this form to create a new Badges.  ",
'invalid_Badges'				=> "The following Badges appears to be invalid:<br />%s",
'pages'				=> "Pages: ",
'single_page'				=> "Single Page",
'Badges_secondary'				=> "Check also in secondary groups?",
'Badges_forums'				=> "Select forums to show badge",
'js_error_occurred'				=> "An error occurred: ",
'Badges_id'				=> "Id",
'submit'				=> "Submit",
'Badges_groups'				=> "Badge applied to",
'ajax_no_Badges'				=> "We were unable to find the Badges with that ID",
'provide_following'				=> "Please provide the following",
'mod_title'				=> "IP.Badges Application",
'Badges_code'				=> "Badge Images",
'Badges_enable'				=> "Active?",
'options'				=> "Options",
'deleted_Badges'				=> "Deleted Badges",
'delete_Badges'				=> "Delete Badge",
'main_page'				=> "Overview",
'edit_Badges'				=> "Edit Badge",
'main_page_detail'				=> "This page lists all currently saved Badges and gives you options to manage them.",
'new_Badges'				=> "Add a new Badge",
'main_page_title'				=> "%s: Overview",
'no_found_Badges'				=> "We could not find the Badges you were attempting to modify.",
'no_badges'				=> "You have not saved any Badges yet",
'badges'				=> "Badges App",
'sure_delete_Badges'				=> "Are you sure you want to delete this Badges?  There is no Undo.",
'create_Badges'				=> "Create Badge",
'message_edit'				=> "Edited Badges",
'message_new'				=> "Added Badges",
'no_Badges_id'				=> "We did not find the Badges you were attempting to edit.",
'no_Badges_title'				=> "You did not enter a Title for the Badges.",
'Badges_link'				=> "Badge Link to:",
 ); 
