<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'suspect_posts_process'				=> "Finding suspect posts, processed %s through %s... ",
'search_complete'				=> "Search complete...",
'suspect_members_process'				=> "Finding suspect members, processed %s through %s... ",
'suspect_members_done'				=> "Finished finding all suspect members...",
'banned_posts_process'				=> "Finding posts associated with banned members, processed %s through %s... ",
'banned_posts_done'				=> "Finished finding all posts associated with banned members... ",
'banned_members_process'				=> "Finding banned members, processed %s through %s...",
'banned_members_done'				=> "Finished finding all banned members...",
'results_cleared'				=> "Old results cleared...",
'new_search'				=> "Start a new Search",
'sbe_blurb'				=> "The table below lists all members who have an IP address (either from registering or posting) that matches an IP address used by a member who has been banned.  This may indicate that this member is a formerly banned member re-registered with a new account.  You can use the tools to the right of their name to manage what you'd like to do with their account, if anything.<br /><br />Use the button above to initiate a new search.  All of your existing data related to the search results below will be purged when you do so.",
'search_performed'				=> "Performed a new search for Ban Evaders",
'no_member_id'				=> "We could not find a member with that ID.",
'member_is_safe'				=> "That member has already been marked as safe.",
'no_group_id'				=> "We could not find a group with that ID.",
'log_member_safe'				=> "Suspected Ban Evaders: Marked member #%s as safe",
'message_member_safe'				=> "Marked member #%s as safe!",
'ip_address_is_safe'				=> "That IP address has already been marked as safe.",
'no_ip_address'				=> "No IP address was passed.",
'message_ban_member'				=> "Banned member #%s!",
'log_ban_member'				=> "Suspected Ban Evaders: Banned member #%s",
'log_ip_address_safe'				=> "Suspected Ban Evaders: Marked IP address %s as safe",
'message_ip_address_safe'				=> "Marked IP address %s as safe!",
'ip_address_is_banned'				=> "That IP address has already been banned.",
'log_ban_ip_address'				=> "Suspected Ban Evaders: Banned IP address %s",
'message_ban_ip_address'				=> "Banned IP address %s!",
'suspected_ban_evaders'				=> "Suspected Ban Evaders",
'ip_addresses_used'				=> "IP Addresses Used",
'suspect_name'				=> "Suspect Name",
'search_results'				=> "Search Results",
'edit_member_profile'				=> "Edit member's profile",
'view_profile'				=> "View Profile",
'look_up_ip'				=> "Look up IP",
'mark_member_safe'				=> "Mark the member as safe",
'move_group'				=> "Move member to the %s group",
'ban_ip_address'				=> "Ban the IP address %s",
'mark_ip_address_safe'				=> "Mark the IP address %s as safe",
'no_ban_evaders'				=> "We could not find any suspected ban evaders",
'options'				=> "Options",
 ); 
