<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'table_columns'				=> "<b>Table Columns: </b>",
'table_headerpos'				=> "<b>Header Position: </b>",
'table_add'				=> "Add Table",
'table_current'				=> "Existing Tables",
'form_table_add'				=> "<b>ADD TABLE</b>",
'form_table_title'				=> "<b>Table Title: </b>",
'form_table_desc'				=> "<b>Short Description: </b>",
'form_table_width'				=> "<b>Table With: </b>",
'form_table_rwidth'				=> "<i> Recommended Width: </i>",
'form_table_tdpos'				=> "<b>Location of the cell content: </b>",
'form_table_tdhpos'				=> "<b>Header position: </b>",
'form_table_addrow'				=> "Add Row",
'form_table_deleterow'				=> "Delete Row",
'form_table_save'				=> "Save Table",
'form_table_bbcodethispost'				=> "BBCodeTables in This Post",
'form_table_edittable'				=> "EDIT TABLE",
'form_table_addtopost'				=> "Add To Post",
'form_table_edit'				=> "Edit Table",
'form_table_delete'				=> "Delete Table",
 ); 
