<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'ffquickban_confirm_start'				=> "You are about to perform the following actions concerning the user <b>%s</b> (id: %d)<br />",
'ffquickban_ip_ban'				=> "<br />IP address will be added to banned IP address list",
'ffquickban_threads'				=> "<br />%d threads started by this user will be %s deleted.",
'ffquickban_posts'				=> "<br />%d posts made by this user will be %s deleted.",
'ffquickban_messages'				=> "<br />%d visitor messages made by this user will be deleted.",
'ffquickban_no_action'				=> "No actions were performed. There was probably nothing to delete. In the case of banning or deleting a user the action may have already been performed.",
'ffquickban_pms'				=> "<br />%d private messages sent by this user will be deleted.",
'ffquickban_delete_reason_input'				=> "Deletion reason:",
'ffquickban_delete_reason'				=> "Spam and/or unwanted content",
'ffquickban_ban_or_delete'				=> "This user will also be %s.",
'ffquickban_ban'				=> "banned",
'ffquickban_delete'				=> "deleted",
'ffquickban_ban_length_select'				=> "Banned for:",
'ffquickban_reason_input'				=> "Ban reason:",
'ffquickban_ban_reason'				=> "Posting unwanted spam",
'ffquickban_confirm_end'				=> "<br /><br />

Please confirm your intentions - <b>This action cannot be undone</b><br /><br />",
'ffquickban_ban_text'				=> "Banned",
'ffquickban_events'				=> "<br />%d calendar events created by this user will be deleted.",
'ffquickban_groupmessages'				=> "<br />%d group messages made by this user will be deleted.",
'ffquickban_user_status'				=> "<br /><br /><strong>User was %s</strong>",
'ffquickban_ip_banned'				=> "IP address %s added to banned IP address list<br />",
'ffquickban_events_deleted'				=> "%d events deleted<br />",
'ffquickban_pms_deleted'				=> "%d private messages deleted<br />",
'ffquickban_posts_deleted'				=> "%d posts deleted<br />",
'ffquickban_threads_deleted'				=> "%d threads deleted<br />",
'ffquickban_email_banned'				=> "Email address %s added to banned IP address list<br />",
'ffquickban_email_ban'				=> "<br />Email address will be added to banned IP address list",
'ffquickban_member_deleted_log'				=> "QuickBan - %s - member deleted - %d - %s",
'ffquickban_member_banned_log'				=> "QuickBan - %s - member banned - %d - %s",
 ); 
