<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'deanban_confirm_start'				=> "You are about to ban the following user <b>%s</b> (id: %d)<br />",
'deanban_no_action'				=> "No actions were performed. There was probably nothing to delete. In the case of banning or deleting a user the action may have already been performed.",
'deanBan_reason_input'				=> "Ban reason:",
'deanban_ban_length_select'				=> "Banned for:",
'deanban_ban'				=> "banned",
'deanBan_ban_reason'				=> "Spamming",
'deanBan_confirm_end'				=> "<br /><br />

Please confirm your intentions - <b>This action cannot be undone</b><br /><br />",
'deanBan_ban_text'				=> "Banned",
'deanBan_user_status'				=> "<br /><br /><strong>User was %s</strong>",
'deanBan_member_banned_log'				=> "DeanBan - %s - member banned - %d - %s",
'deanban_unban'				=> "unbanned",
'deanBan_unban_text'				=> "Member",
'deanBan_member_unbanned_log'				=> "DeanBan - %s - member unbanned - %d - %s",
 ); 
