<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'view_it_anyway'				=> "View it anyway?",
'ignored_comments_not'				=> "This comment is hidden because you have chosen to ignore posts by",
'view_comment'				=> "View comment",
'approve_link'				=> "Approve",
'unhide_link'				=> "Unhide",
'hide_link'				=> "Skrýt",
'edit_link'				=> "Edit",
'delete_link'				=> "Odstranit",
'delete_comment'				=> "Delete comment",
'edit_comment'				=> "Editing comment from:",
'comment_save'				=> "Save",
'delete_x_comments'				=> "Smazat",
'comments_act_go'				=> "Přejít",
'unhide_x_comments'				=> "Unhide",
'hide_x_comments'				=> "Schovat",
'unapprove_x_comments'				=> "Un-approve",
'approve_x_comments'				=> "Approve",
'comment_action_count'				=> "With <span id='comment_count'>#{count}</span> checked comments:",
'manage_comments_pop'				=> "Manage Comments",
'comm_confirm_hide'				=> "Hide Comment",
'comm_confirm_hide_desc'				=> "This option hides the comment, but moderators may still be able to view it.",
'del_comm_now'				=> "Delete comment now",
'comm_confirm_delete_desc'				=> "Are you sure you want to delete this comment?",
'comm_confirm_delete'				=> "Confirm Delete",
'comment_permalink'				=> "Get the permalink",
'comment_approval_required'				=> "Your comment requires moderator approval before it will be shown.",
'comments_header'				=> "Comments",
'click here to login'				=> "Přihlásit se",
'mobile_add_comment'				=> "Přidat komentář",
'yourname_captcha'				=> "Your Name:",
'sign_in'				=> "Přihlásit se",
'post_deleted_by'				=> "Comment Hidden By",
'no_reason_given'				=> "No Reason Given",
'comment_hidden_content'				=> "Toggle Content",
'permalink'				=> "Permalink:",
'comment_reply'				=> "Citace",
'reply_to_comment'				=> "Reply directly to this comment",
'mq_image_add'				=> "Multi-Citace",
'report_link'				=> "Report",
'check_all'				=> "Check all",
'comment_button_post'				=> "Přidat komentář",
'comment_notice_subject'				=> "A new comment has been left on <a href='%s'>%s</a>",
'comment_notifications'				=> "<#NAME#>,

<#AUTHOR#> has just commented on \"<#TITLE#>\", here: <#URL#>.

<div class='callout'><#COMMENT#></div>

You can review the new comment here:
<#COMMENTURL#>",
 ); 
