<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'ah30rep_cancel'				=> "Cancel",
'ah30rep_or'				=> "Or",
'ah30rep_send_rep'				=> "Send",
'ah30rep_says'				=> "says",
'ah30rep_label_entry'				=> "Blog Entry",
'ah30rep_label_image'				=> "Image",
'ah30rep_label_post'				=> "Post",
'ah30rep_negative'				=> "Negative Reputation",
'ah30rep_positive'				=> "Positive Reputation",
'ah30rep_sidebar_title'				=> "Latest Reputation",
'ah30rep_current_rep'				=> "Current Reputation",
'ah30rep_span_message'				=> "Leave blank to 'rep' this person without sending a message",
'ah30rep_no_recent_rep'				=> "You have had no recent reputation since this hook was enabled.",
 ); 
