<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'mi_error_images_writeable'				=> "Some images aren't writeable, see below for details",
'mi_import_failed'				=> "The import failed",
'mi_error_missing_img'				=> "The image %s is missing!",
'mi_error_cannot_write'				=> "The directory %s is not writeable",
'mi_error_doesnt_exist'				=> "The directory %s doesn't exist",
'mi_information'				=> "If you wish to change these images, you can either use the <strong>Import Images XMLArchive</strong> button to import an existing XML Archive or you can upload the images individually to the <strong>%s</strong> directory on your server. If you do choose to manually upload the images, please click the <strong>recache</strong> button when complete.",
'mi_import_title'				=> "Import Images XMLArchive",
'mi_select_xml'				=> "Select XMLArchive",
'mi_upload'				=> "Upload",
'mi_exportxml'				=> "Export as XMLArchive",
'mi_error_no_export'				=> "The export failed",
'mi_tt_size'				=> "Size",
'mi_tt_modified'				=> "Modified",
'mi_tt_filename'				=> "Filename",
'mi_recache'				=> "Recache",
'mi_current_title'				=> "Current Mobile App Images",
'mi_title'				=> "Mobile App iOS Images",
'mi_recache_done'				=> "Recache complete",
'mi_cant_import'				=> "Cannot import",
'mi_img_not_writable'				=> "Not writeable",
'mi_img_not_dims'				=> "Incorrect size, should be %s",
'mi_error_refresh_failed'				=> "Refresh Failed",
 ); 
