<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'enter_username'				=> "Uživatelské jméno",
'enter_useremail'				=> "Email Address",
'enter_name_and_email'				=> "Username / Email",
'ipb_login'				=> "IP.Board: Přihlásit se",
'logout_complete'				=> "Log out complete",
'no_acp_access'				=> "Nemáš oprávnění pro přístup do administrace.",
'bad_email_password'				=> " Vaše zadané jméno nebylo platné.",
 ); 
