<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'abg_todays_birthdays'				=> "Seznam narozenin",
'abg_no_birthdays'				=> "Dnes nikdo nemá z uživatelů narozeniny.",
'auto_birthday_greeter_log'				=> "The follow members have had their birthday today (%s) (%s).",
'abg_global_text1'				=> "would like to wish you a Happy",
'abg_birthday'				=> "Birthday",
'abg_happy_birthday'				=> "Happy Birthday",
'abg_view_profile'				=> "View Profile",
'abg_age'				=> "Věk",
'suffix_rd'				=> "rd",
'suffix_th'				=> "th",
'suffix_st'				=> "st",
'suffix_nd'				=> "nd",
'abg_show_more_birthdays'				=> "Show More Birthdays",
 ); 
