<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'reports_methods_saved'				=> "Your notification preferences have been saved",
'report_ajax_tab_notif_meth'				=> "Notification Methods",
'active_users_members'				=> "%s members:",
'report_option_prune'				=> "Prune Reports...",
'redirect_mark_status'				=> "Marking Reports...",
'redirect_delete_report'				=> "Deleting Reports...",
'active_users_title'				=> "%s user(s) are viewing",
'report_basic_submit'				=> "Odeslat Report",
'report_sending'				=> "Sending Report...",
'report_page_title_unknown'				=> "Unknown Title",
'report_option_delete'				=> "Odstranit reporty",
'report_post_enter'				=> "<strong>Vlož své nahlášení</strong>",
'report_post_url_title'				=> "Předmět",
'report_post_title'				=> "Report this post to a moderator",
'report_basic_desc'				=> "Pozor prosím: tenhle formát nahlášení slouží pouze pro nahlášení uživatelského profilu Staff tým důkladně vyřeší vaší stížnost. <br>Tahle metoda komunikace se staff týmem neslouží k samotné komunikaci, ani žádný jiný důvod.",
'report_basic_enter'				=> "<strong>Vlož své nahlášení</strong>",
'report_basic_url_title'				=> "Reporting Page",
'report_basic_title'				=> "Report this page to a moderator",
'list_header_comments'				=> "Komentáře",
'list_header_reports'				=> "Reports",
'list_header_last_updated'				=> "Last Updated",
'list_header_section'				=> "Section",
'list_header_updated_by'				=> "Updated By",
'list_header_title'				=> "Title",
'list_title'				=> "Reports",
'main_title'				=> "Report Center",
'report_prune_days_box'				=> "days",
'older_than'				=> "older than",
'report_prune_message_none'				=> "Nothing to prune...",
'report_prune_message_done'				=> "Pruning reports...",
'report_mem_msg'				=> "<b>Vlož své nahlášení</b>",
'rss_feed_title'				=> "Report Notification",
'report_actions'				=> "Report Options",
'report_actions_mark_optgroup'				=> "Mark Report As",
'report_mem_title'				=> "Uživatelské jméno",
'report_mem_page'				=> "Nahlásit tenhle profil staff týmu.",
'report_section_title_mem'				=> "Member Profile",
'report_section_title_msg'				=> "Private Message",
'report_section_title_site_downloads'				=> "Download Manager",
'reports_rss_desc'				=> "Shows new reports from the report center.",
'reports_messenger'				=> "Zprávy",
'r_go'				=> "Go",
'r_with_selected'				=> "With selected reports:",
'status'				=> "Status",
'view_content'				=> "View content",
'reporting_title'				=> "Report:",
'post_button'				=> "Odpovědět",
'add_comment_title'				=> "Přidat komentář",
'no_comments_on_report'				=> "There are no comments on this report yet.",
'comments_h2'				=> "Comments",
'posted_prefix'				=> "Odesláno",
'reports_h2'				=> "Reports",
'mark_status_as'				=> "Mark as",
'change_status_title'				=> "Change status",
'change_current_status'				=> "Change Current Status",
'current_status'				=> "Current Status:",
'delete_report'				=> "Odstranit report",
'report_view_reported'				=> "View reported content",
'report_join_pm'				=> "Join the private conversation",
'report_about_pm'				=> "a message titled",
'report_about_intro'				=> "This report is regarding",
'configure_notifications'				=> "Konfigurovat notifikace",
'no_reports'				=> "There are no reports to view",
'view_member'				=> "View member",
'report_updated'				=> "Aktualizováno",
'go_to_section'				=> "Go to section",
'view_report'				=> "View report",
'select_all_reports'				=> "Select all reports",
'reported_content_summary'				=> "Reported content from across your community",
'no_permission_addreport'				=> "You do not have permission to add yourself to private conversations.",
'reports_no_comment_text'				=> "You did not submit a comment to save.",
'reports_no_plugin'				=> "The report center module for the content you are trying to report is not configured correctly.",
'to_view_allrep'				=> "to view all reports.",
'click_here_link'				=> "Click here",
'only_active_note'				=> "Only active reports are currently being displayed.",
'report_prune_2'				=> "days old",
'report_prune_1'				=> "Prune reports older than",
'report_no_title'				=> "No report title",
'invalid_option'				=> "Invalid Option Selected",
'report_comment_saved'				=> "Your comment has been saved successfully",
'report_gallery_comment_suffix'				=> "- Comment",
'report_gallery_image_suffix'				=> "- Image",
'report_file_page'				=> "Report this file to a moderator",
'report_file_title'				=> "File Name",
'report_file_msg'				=> "<strong>Vlož své nahlášení</strong><br /><br />",
'report_msg_page'				=> "Report this message to a moderator",
'report_msg_title'				=> "Private Message Title",
'report_msg_msg'				=> "<strong>Vlož své nahlášení</strong><br /><br />",
'subject_report'				=> "<a href='%s'>%s</a> has <a href='%s'>reported</a> <a href='%s'>something</a>",
'subject_report_guest'				=> "%s has <a href='%s'>reported</a> <a href='%s'>something</a>",
'report_emailpm'				=> "<#MOD_NAME#>,

You have been sent this communication from <#USERNAME#> via the \"Report this to a moderator\" link.

------------------------------------------------

Content Reported: <#LINK#> 
Report Link: <#REPORTLINK#>

------------------------------------------------
Report:

<#REPORT#>

------------------------------------------------
",
'subject_reportreply'				=> "<a href='%s'>%s</a> has <a href='%s'>commented</a> on <a href='%s'>reported content</a>",
'report_reply'				=> "<#MOD_NAME#>,

<#COMMENTER#> has made a comment on a report you have access to in our report center.

------------------------------------------------

Content Reported: <#LINK#> 
Report Link: <#REPORTLINK#>

------------------------------------------------
Comment:

<#COMMENT#>

------------------------------------------------
",
'assign_staff'				=> "Назначить сотрудника",
'unassign_staff'				=> "Отменить назначение %s",
'unassign_staff_general'				=> "Отменить назначение этого пользователя из этого отчета",
'assign_staff_member'				=> "Назначить %s для этого отчета",
'staff_member_assigned'				=> "Сотрудник назначен",
'staff_member_assigned_small'				=> "Сотрудник назначен",
'staff_member_assigned_specific'				=> "%s назначен на этот отчет.",
'staff_member_unassigned_specific'				=> "%s был снят с этого отчета.",
'staff_member_unassigned'				=> "Сотрудник неназначенный из этого доклада",
'staff_member_confirm'				=> "Вы действительно хотите снять назначение этого пользователя?",
'staff_member_myreports'				=> "Мои отчеты",
'staff_member_myreports_desc'				=> "Отчеты предназначены для меня",
'staff_member_allreports'				=> "Посмотреть все отчеты",
 ); 
