<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'help_read_document'				=> "Read document",
'page_title'				=> "Zobrazit téma nápovědy",
'help_topic'				=> "Help Topic",
'help_topics'				=> "Témata nápovědy",
'help_txt'				=> "Vyber si téma ze seznamu, a nebo si vyhledej dané téma.",
'choose_file'				=> "Choose a Topic",
'topic_text'				=> "Here is the topic you chose to view",
'no_help_topics'				=> "There are no help topics yet",
'help_back_list_title'				=> "Back to list",
'help_return_list'				=> "Return to the list of topics",
 ); 
