<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'menu__settings'				=> "Settings",
'menu__manage_pages'				=> "Manage Pages",
'menu__add_new_page'				=> "Add Page",
 ); 
