<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'dp30custompages_error_noactive'				=> "This page is NOT active.",
'dp30custompages_error_noperm'				=> "You don't have permissions to view this page",
'dp30custompages_name'				=> "Page Name",
'dp30custompages_error_noexist'				=> "In our database we didn't find page with this ID.",
'dp30custompages_id'				=> "#ID",
'dp30custompages_updated'				=> "Date updated",
'dp30custompages_added'				=> "Date added",
'dp30custompages_see_page'				=> "Show page",
'dp30custompages_date_updated'				=> "Date updated: ",
'dp30custompages_date_added'				=> "Date added: ",
'dp30custompages_error_disable'				=> "This application is off-line now",
'dp30custompages_error_group'				=> "You don't have permissions to view this page",
'dp30custompages_error_nopages'				=> "No pages",
'dp30custompages_error_wrongid'				=> "Wrong ID. Please try again.",
 ); 
