<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'do_raw_html'				=> "Enable RAW HTML/JS mode?",
'error_no_id'				=> "No ID Provided!",
'perms'				=> "Permissions",
'general_config'				=> "General Configuration",
'boxed'				=> "Boxed",
'recache_blocks'				=> "Recache Blocks",
'enter_content_below'				=> "Enter Content to Display Below",
'enter_content_below_exp'				=> "HTML and BBCODE are OK!",
'image'				=> "Image",
'editing'				=> "Editing",
'use_perms'				=> "Use Permission Matrix Below?",
'use_perms_exp'				=> "Leave at no to disregard below settings",
'image_name'				=> "Full Image Name (with extension).",
'image_name_exp'				=> "Works with any image in the .public/style_images/master directory.  You can also use an image from within a subdirectory in master, E.G. <i>new images/my_image.png</i> as long as that directory is in the style_images/master folder.",
'use_box_exp'				=> "Leave off to simply show the content with no surrounding html.",
'use_box'				=> "Use Table/Border/Title/Image?",
'title_exp'				=> "Displays in the block header.",
'display_content'				=> "Display Content",
'enabled'				=> "Enabled?",
'enabled_exp'				=> "Leave off to not show currently.",
'do_raw_html_exp'				=> "If enabled, NO PARSING will occur.  Good if you want to show html/javascript only, such as an embeded widget or a banner.",
'and_reload'				=> "and Reload",
'preview'				=> "Preview",
'php_based'				=> "Enabled PHP mode?",
'php_based_exp'				=> "If enabled, and above Raw Mode is disabled, entire block contents needs to be in PHP.  You need to return the html to be displayed, and do not use echo, print, etc.  And do not use open/closing php tags.<br />
	  All standard IPB objects are available (registry, DB, memberData, cache, settings, request, etc).",
'export_block'				=> "Export Block",
'raw_mode'				=> "Raw Mode?",
'php_mode'				=> "PHP Mode?",
'collapsible'				=> "Collapsible?",
'error_none_found'				=> "No blocks found by that ID!",
'blocks_recached'				=> "Blocks Recached!",
'add_new_block'				=> "Add New Block",
'delete_block'				=> "Delete Block",
'block_added'				=> "Block Added!",
'block_edited'				=> "<%NAME%> Block Edited!",
'blocks_page'				=> "Manage Custom Sidebar Blocks",
'block_deleted'				=> "Block Deleted!",
'options'				=> "Nastavení",
'edit_block'				=> "Edit Block",
'add_block'				=> "Add Block",
'adding_block'				=> "Adding New Custom Sidebar Block",
'block_title'				=> "Block Title",
'block_details'				=> "Block Details",
'custom_sidebar_blocks'				=> "Custom Sidebar Blocks",
'hide_collapse_ability'				=> "Remove Ability for User to Collapse Block?",
'hide_collapse_ability_exp'				=> "If enabled, user will be forced to view block, good for advertisements and donation links, etc.",
'parsing_options'				=> "Parsing Options",
'hide_from_main_block'				=> "Hide from main custom block?",
'hide_from_main_block_exp'				=> "If yes, this block will be skipped when displaying all the custom blocks in the index (good if you have exported this block and imported the resulting hook and want to use it's placement instead.)",
 ); 
