<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'submit_form'				=> "Odeslat žádost",
'no_fields_display'				=> "There are currently no fields to display.",
'g_fs_moderate_logs'				=> "Can moderate form submissions?",
'g_fs_view_logs'				=> "Can view form submissions?",
'g_fs_allow_attach'				=> "Can upload attachments?",
'seconds'				=> "seconds",
'g_fs_bypass_captcha'				=> "Bypass captcha checks?",
'enter_zero_disable'				=> "Enter zero to disable!",
'g_fs_view_offline'				=> "Can view offline form manager?",
'g_fs_submit_wait'				=> "Time before can resubmit form?",
'basic_permissions'				=> "Basic Permissions",
'view_logs'				=> "View Logs",
'view_form'				=> "View Form",
 ); 
