<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'leader_forums'				=> "Fórum",
'leader_group'				=> "Skupina",
'leader_last_seen'				=> "Poslední aktivita",
'leader_name'				=> "Uživatel",
'forum_leaders'				=> "Moderátorský tým",
'top_poster_title'				=> "Today's top 20 posters",
'no_info'				=> "No information is available at this time",
'member_percent'				=> "% of today's posts",
'member_joined'				=> "Registrován",
'member_today'				=> "Posts Today",
'member_posts'				=> "Total Member Posts",
'member'				=> "Member",
'todays_posters'				=> "Today's Top 20 Posters",
'goto_profile'				=> "Go to profile",
'whoposted_posts'				=> "Posts",
'whoposted_name'				=> "Uživatelské jméno",
'no_forums'				=> "View %s Forums",
'who_farted'				=> "Who posted in:",
'who_replied_title'				=> "Who posted in this topic",
'go_button'				=> "Přejít",
'm_online'				=> "Online",
'leader_all_forums'				=> "Všechna fóra",
'stats_missing_tid'				=> "You must select a valid topic for this feature",
'notopic_attach'				=> "Could not load attachments for the requested topic",
'topic_noattach'				=> "The specified topic does not have any attachments",
'topic_noperms'				=> "You do not have permission to access this forum",
 ); 
