<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'bbc_after'				=> "We Show",
'bbc_before'				=> "You Type",
'bbc_title'				=> "BB Code",
'bbc_intro'				=> "BB Code is a quick and easy way to add effects or formatting to your posts.<br />It is used in a similar format to HTML tags which you may already be familiar with.<br />Below is a quick guide to the most common BB Code uses.",
'emo_title'				=> "Emoticons",
 ); 
