<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'forumicons_overview'				=> "Forum Icons Overview",
'update_cache'				=> "Update Cache",
'forums'				=> "Forums",
'edit_settings'				=> "Edit Forum",
'noforums'				=> "Can't find any forum.",
'tools_list'				=> "Tools List",
'convert_tool_title'				=> "Convert Old Settings",
'convert_tool_title_desc'				=> "With this tool you can convert old settings to the new system of forum icons.",
'run_tool'				=> "Run Tool",
'convert_tool_run'				=> "Old settings were converted successfully.",
're_percycle'				=> "Per Cycle",
'success_cache_updated'				=> "Icons cache was updated successfully.",
'edit_item_button'				=> "Edit Forum",
'editing_item'				=> "Editing Forum Icon",
'error_no_forum_id'				=> "Can't find this forum. Please try again.",
'oror'				=> "<strong>...or...</strong>",
'cancel_operation'				=> "Cancel Operation",
'redirectedit_item'				=> "Forum icon was edited successfully.",
'main_informations'				=> "Main Informations",
'i_enabled'				=> "Enabled",
'i_enabled_desc'				=> "Do you want to show custom icon for this forum?",
'icon'				=> "Icon",
'icon_desc'				=> "Select icon and upload it.",
'error_number__upload_failed_possible_xss'				=> "Possible XSS attack!",
'error_number__upload_no_choosen_file'				=> "You didn't select file to upload.",
'error_number__invalid_file_extension'				=> "Invalid file extension.",
'error_number__upload_to_big'				=> "File what you trying upload is too big.",
'error_number__upload_failed_cant_move'				=> "Can't move file.",
'error_number__upload_failed_no_upload'				=> "Failed upload. Please try again.",
'current_image'				=> "Current Image",
'rebuild_process_f'				=> "Processed forum %s ",
're_rebuildcomp'				=> "<strong>Rebuild completed</strong><br /> ",
're_thisgoeshere'				=> "<strong>Up to %s processed so far, continuing...</strong>",
'delete_icon'				=> "Delete Icon",
'success_icon_deleted'				=> "Icon was deleted successfully.",
'error_no_icon_field'				=> "No 'icon' field. This tool can't be used.",
 ); 
