<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'copy_from'				=> "Copy this topic from forum ",
'copy_exp'				=> "Please, select the destination forum. You may choose some options if you want.",
'top_copy'				=> "Copy topic",
'copy_topic_options'				=> "Options",
'to'				=> "to",
'post_count'				=> "User post count incrementation ?",
'submit_copy'				=> "Copy Topic",
'novo_titulo'				=> "New title (optional)",
'nova_desc'				=> "New description (optional)",
'topic_state'				=> "Topic state",
'topic_state_open'				=> "Open",
'topic_state_closed'				=> "Closed",
'topic_approved'				=> "Topic visibility",
'topic_approved_visible'				=> "Visible (approved)",
'topic_approved_invisible'				=> "Invisible (unapproved)",
'multimod'				=> "Multi-moderation",
'topico_copiado'				=> "The topic was copied! Returning you to the new topic.",
'padrao'				=> "- Topic Value -",
'topic_pinned'				=> "Pin/Unpin topic",
'topic_pinned_pinned'				=> "Pinned topic",
'topic_pinned_unpinned'				=> "Unpinned topic",
'novo_autor_opcional'				=> "New author (optional)",
'copiar_topico'				=> "Copy topic",
'autoria_alterada'				=> "Topic author changed",
'mudar_posts'				=> "Change all posts authored by the original topic's author made this topic ?",
'mudar_autoria'				=> "Change Author",
'novo_autor'				=> "New Author",
'mudar_autor_title'				=> "Change Topic Author",
'informacoes_atuais'				=> "Current Topic Information",
'move_topic'				=> "Move topic",
 ); 
