<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'tcdl_success'				=> "%s topics closed and marked for deletion more than %s days ago, have been deleted.",
'tcdl_no_topics'				=> "No topics found for deletion.",
 ); 
