<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'cookie__galuploader'				=> "Gallery Uploader Choice",
'cookie__galuploader__desc'				=> "Set when toggling between the std/Flash uploaders",
'cookie__gal_pids'				=> "Gallery Image IDs",
'cookie__gal_pids__desc'				=> "Set when selecting images to moderate",
 ); 
