<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'r__galstats_memberalter'				=> "Can change member access privileges?",
'r__galstats_groups'				=> "Can run group reports?",
'r__galstats_filealter'				=> "Can change file ownership?",
'r__galstats_files'				=> "Can run file reports?",
'r__galstats_members'				=> "Can run member reports?",
'r__stats_reports'				=> "Stats Reports",
'r__category_empty'				=> "Can empty categories?",
'r__category_delete'				=> "Can delete categories?",
'r__category_manage'				=> "Can add and edit categories?",
'r__album_delete'				=> "Can delete albums?",
'r__category_managet'				=> "Category Management",
'menu__gallery_overview'				=> "Overview",
'r__album_empty'				=> "Can empty albums?",
'r__album_manage'				=> "Can edit and resynchronize album information for members?",
'r__album_add'				=> "Can add albums for members?",
'r__album_managet'				=> "Album Management",
'menu__gallery_settings'				=> "Settings",
'menu__gallery_album_defautls'				=> "Albun Defaults",
'menu__gallery_stats'				=> "Statistics",
'menu__gallery_add_album'				=> "Add New Album",
'menu__gallery_album_manager'				=> "Album Manager",
'menu__gallery_category_manager'				=> "Category Manager",
 ); 
