<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'ja_edit_location'				=> "Display Location",
'ja_edit_location_desc'				=> "Where awards will be displayed",
'ja_edit_perm'				=> "Public Awarding Permissions",
'ja_edit_perm_desc'				=> "Which groups can publicly award this award? (Not applicable for Badges)",
'ja_edit_savechanges'				=> " Save Changes ",
'ja_edit_saveor'				=> "or",
'ja_enable'				=> "Enable",
'ja_enabledisable'				=> "Enable/Disable",
'ja_helppage'				=> "Help Using this Page",
'ja_helpshowhide'				=> "Show/Hide Information",
'ja_hide'				=> "Hide",
'ja_mahelp'				=> "This page allows you to manage your awards, and the categories which your awards reside in. In an attempt to limit the amount of time you have to wait for pages to load, I have included some quick AJAX functionality. The sections below cover each function you may want to do.
<br />
<br />
<strong style='text-decoration:underline;'>Altering Category Titles:</strong>
<br />
To edit a category's title you must double click the title, and then a text box will appear. To save or cancel, click in the box and then click out of it. (TIP: To retrieve the original value, erase the field and then save it.)
<br />
<br />
<strong style='text-decoration:underline;'>Changing Order of Awards and Categories:</strong>
<br />
Just like other pages in this Admin CP, you can use the drag handel icon to alter the order of the categories and awards on this page.
<br />
In the case of some Award category types (eg Badge) the order of the Awards decides which image will be displayed if the user has multiple Award images when only one is allowable.
<br />
<br />
<strong style='text-decoration:underline;'>Changing Visibility of Awards and Categories:</strong>
<br />
If you would like to hide an award, or a category, you can! To do this just click the check mark (%enabledImage%), or the cross (%disabledImage%). The check will appear if the award/category is currently enabled, and the cross is just the opposite. You will not be able to enable categories which do not have any awards in them.
<br />
<br />
<strong style='text-decoration:underline;'>Changing Visibility inside the Awards Cabinet:</strong>
<br />
In addition to enabling/disabling Awards and Categories you are able to hide Awards from the display cabinet. Just click the eye %showImage% - Visible or %hideImage% - Hidden. This is especially designed to allow for non-award graphics to be added for users.",
'ja_edit_icon_warn'				=> "Leave this blank to not change the award's icon!!!",
'ja_edit_icon_desc'				=> "This is the image representation for this award. It should be about 40x40 pixels, only upload image files.",
'ja_edit_icon'				=> "Award Icon",
'ja_edit_cattitle_desc'				=> "",
'ja_edit_cattitle'				=> "Change Category Title",
'ja_edit_badge_desc'				=> "Which groups will have this badge displayed (only effective for award in the badge grouping)",
'ja_edit_badge'				=> "Badge Group",
'ja_edit_awardname_desc'				=> "The award will be identified by this",
'ja_edit_awardname'				=> "Award Name",
'ja_edit_awardlongdesc_desc'				=> "Long description (html allowed) for use in Cabinets.",
'ja_edit_awardlongdesc'				=> "Long Description",
'ja_edit_awarddesc_descno'				=> "Text to diplay to explain how to get this award in the unAwarded/Achievement boxes only.",
'ja_edit_awarddesc_desc'				=> "Brief description about this award.",
'ja_edit_awarddescno'				=> "Tooltip for unAwarded/Achievement display",
'ja_edit_awarddesc'				=> "Short Description",
'ja_edit_awardcategory_desc'				=> "Choose the category you want this award to be placed into.",
'ja_edit_awardcategory'				=> "Category",
'ja_edit_award'				=> "Editing Award:",
'ja_editcat_title'				=> "Edit this Category",
'ja_editcat'				=> "Edit Category",
'ja_editaward'				=> "Edit Award:",
'ja_edit'				=> "Edit",
'ja_disable'				=> "Disable",
'ja_doubleclick'				=> "Double Click to Edit",
'ja_dirwrite'				=> "Please make sure that the directory \"auto_awarding\" is readable by your system",
'ja_deletecat_title'				=> "Delete this Category",
'ja_delhasawards'				=> "This category has awards, what do you want to do with them? &nbsp;&nbsp;&nbsp; ",
'ja_deletecatno'				=> "Can&apos;t delete the default Category",
'ja_submit'				=> "Submit",
'ja_deletecat'				=> "Delete Category",
'ja_delete'				=> "Delete",
'ja_delcat'				=> "Deleting Category",
'ja_delaward'				=> "Are you sure that you would like to delete this award, this action cannot be undone.",
'ja_delareyousure'				=> "Are you sure that you would like to delete this category, this action cannot be undone.",
'ja_continue'				=> " Continue ",
'ja_auto_awards'				=> "Auto Awarding Managment",
'ja_cancel'				=> "Cancel",
'ja_autotype'				=> "Auto-Award Type",
'ja_addnewcat'				=> "Add New Category",
'ja_addnewaward'				=> "Add New Award",
'ja_addingaward'				=> "Adding Award",
'ja_addaward'				=> " Adding Award ",
'ja_addauto'				=> "Add New Auto-Award Function",
'ja_addaatype'				=> "Auto-Award Type",
'ja_addaafun'				=> "Adding New Auto-Award Function",
'ja_manage_awards'				=> "Manage Awards",
'ja_noaafun'				=> "There aren't any auto-award functions.",
'ja_ormoveto'				=> "or move to....",
'ja_pleasechooseone'				=> "Please Choose One",
'ja_show'				=> "Show",
'ja_show_on_frontend'				=> "Show on Frontend",
'ja_show_on_frontend_desc'				=> "Should this category be listed in the Awards Cabinet",
'ja_type_achievement'				=> "Achievement",
'ja_type_badge'				=> "Badge",
'ja_type_naked'				=> "Naked",
'ja_type_profile'				=> "Profile",
'ja_type_signature'				=> "Signature",
'ja_yesdelete'				=> "Yes, Delete",
'ja_cabinet_permissions'				=> "Cabinet View Permissions",
'ja_manage_cabinet'				=> "Manage Cabinet Permissions",
 ); 
