<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'error_no_awards'				=> "Momentálně zde nejsou dostupná žádná ocenění pro vás.",
'description'				=> "Popis",
'awards_title_post'				=> "Ocenění",
'awards_signature_post'				=> "Ocenění",
'awards_profile_view_title'				=> "Ocenění",
'awards_profile_tab_title'				=> "Ocenění",
'award'				=> "Ocenění",
'no_awards'				=> "Žádná ocenění",
'profile_public_award'				=> "Udělit ocenění",
'statistics'				=> "Informace",
'title'				=> "Ocenění",
'last_awarded'				=> "Last Awarded",
'hide_awarded'				=> "Hide Awarded",
'give_award_title'				=> "Giving an Award to",
'give_award_msg'				=> "Please choose an award to give from the menu, you may also add notes to this award if you'd like.",
'give_award_continue'				=> "Give Award",
'given_by_unknown'				=> "Unknown",
'error_no_permission'				=> "You do not have permission to access this page",
'error_no_awarded'				=> "There aren't any users with this award",
'error_listings_disabled'				=> "Sorry, but the board administrator has disabled this page.",
'error_invalid_request'				=> "The URL you have followed is invalid",
'enter_award_notes'				=> "Notes",
'choose_award'				=> "Choose an Award",
'award_removed'				=> "Award Removed",
'award_info'				=> "Name / Description",
'award_icon'				=> "Award Image",
'award_given_on'				=> "Given on",
'award_given_by'				=> "by",
'award_added'				=> "Award Added",
'awards_profile_view_unawarded'				=> "Not yet awarded",
'awards_achievement_post'				=> "Achievements",
'awarded'				=> "Awarded",
'pending_approval'				=> "Pending Approval",
'remove_award'				=> "Remove Award",
'times_awarded'				=> "Times Awarded",
'view_awarded'				=> "View Awarded",
 ); 
