<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'group_name_indicator'				=> "Group Name Indicator",
'shown_groups'				=> "Shown Groups",
'no_toggle_guest'				=> "Can&#39;t toggle the Guest group",
'm_display_order'				=> "Manage Display Order",
'disable'				=> "Disable",
'enable'				=> "Enable",
'enabled'				=> "Enabled",
'g_hidden'				=> "hidden",
'g_shown'				=> "shown",
'g_successfully'				=> "The group was successfully ",
'g_title'				=> "Group Title",
'postform_badmd5'				=> "Bad key supplied",
'hidden_groups'				=> "Hidden Groups",
 ); 
