<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'WHERE_print'				=> "Printing a topic",
'WHERE_search'				=> "Searching...",
'WHERE_help'				=> "Viewing the Help Files",
'WHERE_members'				=> "Viewing the Members List",
'WHERE_online'				=> "Prohlíží seznam online uživatelů",
'WHERE_reg'				=> "Registering...",
'WHERE_postrep'				=> "Odesílá příspěvek v tématu:",
'WHERE_postnew'				=> "Posting in forum:",
'WHERE_login'				=> "Přihlašování...",
'WHERE_st'				=> "Prohlíží si téma:",
'WHERE_sr'				=> "Viewing Forum Rules:",
'WHERE_sf'				=> "Viewing Forum:",
'WHERE_portal'				=> "Viewing the portal",
'WHERE_boardrules'				=> "Viewing Community Guidelines",
'WHERE_calendar'				=> "Viewing the Calendar",
'not_online'				=> "Not online",
'board_index'				=> "Hlavní stránka fóra",
'no_options_available'				=> "Žádná nastavení nejsou k dispozici",
'users_online'				=> "Users online",
'online_page_title'				=> "Online uživatelé",
'where'				=> "Lokace",
'time'				=> "Čas",
'member_name'				=> "Uživatel",
's_go'				=> "Aktualizovat",
's_show_mem_all'				=> "Zobrazit všechny uživatele",
's_show_mem_reg'				=> "Zobrazit pouze registrované",
's_show_mem_guest'				=> "Zobrazit pouze návštěvníky",
's_sort_order_desc'				=> "Sestupně",
's_sort_order_asc'				=> "Vzestupně",
's_sort_key_name'				=> "Uživatelské jméno",
's_sort_key_click'				=> "Poslední kliknutí",
's_by'				=> "<font color=\"white\"><strong>Seřazeno podle:</strong></font> ",
'WHERE_forward'				=> "Emailing a topic",
'WHERE_msg'				=> "Using Personal Messenger",
'WHERE_usercp'				=> "Using User CP",
'WHERE_mail'				=> "Contacting member via email",
'WHERE_invite'				=> "Inviting a friend to the community",
'WHERE_profile'				=> "Prohlíží si profil:",
'WHERE_stats'				=> "Viewing Stats",
'WHERE_reports'				=> "Viewing Reports",
 ); 
