<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'exp_0'				=> "Never",
'exp_1209600'				=> "2 Weeks",
'exp_86400'				=> "1 Day",
'exp_15811200'				=> "6 Months",
'exp_2592000'				=> "1 Month",
'exp_31536000'				=> "1 Year",
'exp_43200'				=> "12 Hours",
'exp_3600'				=> "1 Hour",
'exp_600'				=> "10 Minutes",
'exp_604800'				=> "1 Week",
'exp_7862400'				=> "3 Months",
 ); 
