<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'subject__pmviewer_keyword_notification'				=> "<a href='%s'>%s</a> has sent a %s containing a flagged keyword.",
'subject__pmviewer_keyword_notification_msg'				=> "<a href='%s'>%s</a> has sent a %s containing a flagged keyword.",
'pmviewer_keyword_notification'				=> "<#NAME#>,

<#AUTHOR#> has just sent a message featuring one of the specified keywords you are monitoring conversations for. <#TEXT#>

======================================================================
You can turn off this notification by visiting <#URL#>
",
'pmviewer_keyword_notification_msg'				=> "<#NAME#>,

<#AUTHOR#> has just sent a message featuring one of the specified keywords you are monitoring conversations for. <#TEXT#>

In the conversation entitled \"<#TITLE#>\", <#AUTHOR#> said:
======================================================================
<#MESSAGE#>
======================================================================

You can turn off this notification by visiting <#URL#>
",
'notify__pmviewer_keyword_monitor'				=> "Notify me of conversations containing keywords specified in (SN) PM Viewer",
'pm_keyword_link_text'				=> "You can view the conversation by logging into the ACP using this link:",
'pm_keyword_nolink_text'				=> "The conversation id is",
'pm_keyword_nolink_msg'				=> "message",
 ); 
