<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'sospromote_novip'				=> "<font color=\"white\"><strong>Nebyli momentálně nalezení žádní uživatele se statusem VIP!</strong></font>",
'membros_vips'				=> "VIP Uživatelé",
'visao_geral'				=> "Overview",
'add_secondary'				=> "VIP in Secondary Groups?",
'situacao'				=> "TOP 5 Last Days as VIP Members",
'situacao_geral'				=> "General Stats",
'situacao_geral_valor'				=> "Value",
'situacao_geral_stats'				=> "Stat",
'versao'				=> "Version",
'autor'				=> "Author",
'mod'				=> "About",
'site'				=> "Site",
'add_member'				=> "New VIP Member",
'overview_membro'				=> "Display Name",
'overview_groupooriginal'				=> "Original Group",
'overview_dias'				=> "Remaining Days",
'overview_final'				=> "Ends on",
'overview_acoes'				=> "Actions",
'add_titulo'				=> "Promotion Details",
'add_user'				=> "User",
'add_dias'				=> "Days",
'add_vippermanente'				=> "Permanent VIP?",
'add_promotemember'				=> "Promote Member",
'add_nomevazio'				=> "ERROR: You didn't select a member!",
'add_diaserrado'				=> "ERROR: You didn't type or filled wrongly the number of days!",
'add_nouser'				=> "ERROR: We couldn't locate that member!",
'add_jaevip'				=> "ERROR: This is user is a VIP Member already!",
'add_promoteok'				=> "The member was promoted successfully!",
'add_nouserselecionado'				=> "ERROR: You didn't select a user to demote!",
'add_demoteok'				=> "This user was demoted successfully!",
'add_nogroups'				=> "ERROR: You didn't set the VIP Group yet! Click on SETTINGS link at left!",
'manage_member'				=> "Manage VIP Members",
'add_editmember'				=> "Edit",
'comselecionados'				=> "With selected",
'add_nouserselecionadoedit'				=> "ERROR: You didn't select users to edit their remaining days!",
'add_membersedited'				=> "Remaining days changed for the selected users!",
'search_search'				=> "Search",
'search_main'				=> "VIP Members Search",
'search_where'				=> "Search by",
'search_ln'				=> "Login Name",
'search_dn'				=> "Display Name",
'search_id'				=> "Member ID",
'search_email'				=> "Email",
'overview_id'				=> "ID",
'wrong_period'				=> "The number of days you're trying to change is bigger or equal to the days that this user still have as VIP Member!",
'add_group'				=> "VIP Group",
'add_grupop'				=> "This user belongs to a protected group and can't be promoted to any VIP Member group",
'no_permission'				=> "You do not have permission to access this page",
 ); 
