<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.4.9 (34015) on Mon, 26 Jun 2017 18:07:24 +0000 by nV1diaX
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'frm_m_group'				=> "-- OR -- select a group",
'frm_m_topicId'				=> "Enter the ID of the topic he/she can moderate",
'frm_m_moderateOwn'				=> "Can moderate own topics?",
'frm_m_moderateOwn_desc'				=> "This will add the member or group as moderator to all topics started by them.",
'frm_m_modOptions'				=> "Moderator Options",
'frm_m_allForums'				=> "-- ALL FORUMS --",
'frm_m_forumDesc'				=> "You may choose more than one.",
'frm_m_forums'				=> "Restrict it to the following forums:",
'frm_m_memberName'				=> "Enter the members display name",
'frm_m_topic'				=> "Can edit topic title?",
'gf_bw_soft_delete_see_post'				=> "Can see 'Soft Deleted' content for posts",
'gf_bw_soft_delete_reason'				=> "Can see 'Soft Deleted' reason for posts",
 ); 
